### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by marph91** [jfcostello/AnyBlock-To-Markdown#2]
Hi, are there any plans for a release on [pypi](https://pypi.org/)? I'm thinking of integrating the AnyType to Markdown conversion to [jimmy](https://github.com/marph91/jimmy).

**Comment by jfcostello** [comment]
That's my first time seeing that Jimmy project, that is really, really cool.

Honestly, I hadn't considered pypi at all. I'm not any kind of competent developer, so mostly leveraged LLMs to parse through and make sense of AnyBlock, and then build the exporter which probably still needs some polish. I'd happily have it be part of Jimmy, or any project, if anyone gets use from it go for it and use it however you see fit. 

I haven't a whole lot of time in the coming weeks but it's definitely something I can look into, as well as stress testing it a bit more. To be honest, I built it to get it to a point where it could free my notes, and I haven't spent much time on it since then, but I'd definitely be willing to spend a bit of time if it could help others get their notes into a universal format

**Comment by marph91** [comment]
> Honestly, I hadn't considered pypi at all.

That's fine. Maybe I can integrate it as git submodule first to see how the interface could look like and if it's possible at all.

> mostly leveraged LLMs to parse through and make sense of AnyBlock, and then build the exporter which probably still needs some polish.

In general I'm not a big fan of using AI for coding, but at the first glance the code looks well. Since the inputs are fixed and the output is constrained by the Markdown standard(s), it might be a good task for AI.

Can I ask which tools you used for generating the code? I'm interested and might take a look at them.

> I haven't a whole lot of time in the coming weeks

No problem. At the end, most of us are doing this in our free time :)

**Comment by jfcostello** [comment]
> That's fine. Maybe I can integrate it as git submodule first to see how the interface could look like and if it's possible at all.
 
For sure! If you have time, go for it! I'm not sure when I'll have much time to spend on this for a bit

> In general I'm not a big fan of using AI for coding, but at the first glance the code looks well. Since the inputs are fixed and the output is constrained by the Markdown standard(s), it might be a good task for AI.

> Can I ask which tools you used for generating the code? I'm interested and might take a look at them.

I'm pleasantly surprised you'd say that! I've very little direct coding experience, but I have been a Product Manager for years, so generally know enough to know how the project should be structured, how to reign the tools in and keep them going off the deep end and have somewhat of an idea what decent code looks like. That said, for this one, I paid less attention than normal since I was really building something just good enough for one specific use case initially - move my own notes out. So I'm surprised you don't think it's a complete mess

For tools, I used Gemini [via the studio](https://aistudio.google.com) to figure out Anyblock, since it's so damn verbose I needed something with an incredibly large context window to be able to fully grasp it. Primarily, Geminis role was to document the structure of Anyblock, and how an export tool should work

I used Claude to do most of the coding using Geminis instructions, as at the time it was the strongest coding model (And may still be)

Back then I was just using a VSCode extension called prompt tower to copy and paste into the web tools, but now I use tools like Cursor to save the effort

> No problem. At the end, most of us are doing this in our free time :)

For sure! That's why I'm happy for you to take this and do whatever you want with it if it helps people, if there is something you need from my end though let me know, I won't have time in the short term but will do hopefully closer to the end of the year
